export const HERO_CLASSES = [
	{
		id: 1,
		name: 'Warrior',
		emoji: '⚔️',
		summary: 'Brave, relentless, and mighty',
		preferredWeaponTypes: ['sword', 'axe', 'mace'],
		starterAssignments: { utility: 'bread' },
		mods: { str: 3, agi: -1, sta: 0, hp: 1, wis: -2, int: -1, per: 0, luk: 0, hun: 0 },
	},
	{
		id: 2,
		name: 'Rogue',
		emoji: '🗡️',
		summary: 'Sneaky, agile, and cunning',
		preferredWeaponTypes: ['dagger', 'rapier', 'bow'],
		starterAssignments: { longrange: 'throwing_stone', carrier: 'utility_satchel', utility: 'small_health_potion' },
		mods: { str: 0, agi: 3, sta: 0, hp: -1, wis: -1, int: 0, per: 0, luk: 2, hun: -3 },
	},
	{
		id: 3,
		name: 'Mage',
		emoji: '🪄',
		summary: 'Wise, perceptive, and curious',
		preferredWeaponTypes: ['staff', 'wand', 'scepter'],
		starterAssignments: { utility: 'mysterious_scroll' },
		mods: { str: -1, agi: 0, sta: -1, hp: -2, wis: 4, int: 1, per: 2, luk: 1, hun: -4 },
	},
	{
		id: 4,
		name: 'Cleric',
		emoji: '⛪',
		summary: 'Faithful, steady, and protective',
		preferredWeaponTypes: ['mace', 'staff', 'scepter'],
		starterAssignments: { ring: 'ring_of_satiety', utility: 'small_health_potion' },
		mods: { str: -1, agi: 0, sta: 0, hp: 0, wis: 2, int: 3, per: 1, luk: 0, hun: -5 },
	},
	{
		id: 5,
		name: 'Ranger',
		emoji: '🏹',
		summary: 'Sharp, patient, and precise',
		preferredWeaponTypes: ['bow', 'dagger', 'spear'],
		starterAssignments: { longrange: 'throwing_stone', utility: 'bread' },
		mods: { str: 0, agi: 2, sta: 0, hp: -1, wis: -1, int: 0, per: 0, luk: 2, hun: -2 },
	},
	{
		id: 6,
		name: 'Bard',
		emoji: '🎵',
		summary: 'Charming, inspiring, and clever',
		preferredWeaponTypes: ['rapier', 'dagger', 'wand'],
		starterAssignments: { utility: 'mysterious_scroll', carrier: 'utility_satchel' },
		mods: { str: 0, agi: 1, sta: 0, hp: -1, wis: 1, int: 0, per: 2, luk: 1, hun: -4 },
	},
	{
		id: 7,
		name: 'Paladin',
		emoji: '🛡️',
		summary: 'Honorable, fearless, and loyal',
		preferredWeaponTypes: ['sword', 'mace', 'hammer'],
		starterAssignments: { artifact: 'shark_tooth_necklace', utility: 'small_health_potion' },
		mods: { str: 2, agi: 0, sta: 1, hp: 2, wis: -1, int: 2, per: -1, luk: 0, hun: -5 },
	},
	{
		id: 8,
		name: 'Monk',
		emoji: '🥋',
		summary: 'Focused, disciplined, and swift',
		preferredWeaponTypes: ['fist', 'staff', 'nunchaku'],
		starterAssignments: { utility: 'bread' },
		mods: { str: 1, agi: 2, sta: 2, hp: 0, wis: -2, int: 0, per: -1, luk: 0, hun: -2 },
	},
];
